import os
import json
import asyncio
import pathlib
import tempfile
from typing import NewType

import dffml


def get_argument_datatype(func: Callable, name: str) -> Type:
    """
    >>> def feedface(a: str):
    ...     pass
    >>> get_argument_datatype(feedface, "a")
    <class 'str'>
    """
    return inspect.signature(func).parameters()[name].param_annotation


# Alice:
# - Ensure that the repository never has more than 1 commit from being sorted by
#   date with latest change as given by date field being the most recent commit.
# - If no edits, commit the file at whatever the created at date is.
# - If there are edits, ensure they are committed to the file in the correct
LockingTypeHints = NewType("LockingTypeHints", Union)
ReadWriteLock = NewType("ReadWriteLock", LockingTypeHints)

GitRepository = NewType("GitRepository", ReadWriteLock[GitRepoSpec])
GitRepositoryCheckedOut = NewType("GitRepositoryCheckedOut", ReadWriteLock[GitRepoCheckedOutSpec])

DateToCommitGitRepoFileAt = NewType("DateToCommitGitRepoFileAt", str)

FilePath = NewType("git_set_file_contents_at_date.FilePath", Union[str, pathlib.Path])


class SystemContextOpConfig:
    system_context: SystemContext


@op(
    config_cls=SystemContextOpConfig,
)
def git_set_file_contents_at_date(
    # When we serialize to/from web3 we'd see the repo object and the output of
    # this function be treated as NFTs, because we leverage NFTs for distriuted
    # locking. Can even get distributed semaphore functionality by leveraging
    # NFTs if you have a finite non 0/1 number of them
    repo: ReadWriteLock[GitRepository],
    date: DateToCommitGitRepoFileAt,
    filepath: FilePath,
) -> ReadWriteLock[GitRepositoryCheckedOut]:
    """
    Given a Git repository, set the contents of the given filepath to be the
    given contents within a commit with the date field matching the given date.

    We take the read write lock on the git repo when it comes in. Aka the caller
    should lock that object before calling this function! We also signal to the
    caller that if they use the returned object it we recommend that they lock
    it! If don't want to, that's up to them, but we recommend you lock it. As
    the producing operation, we understand that what we are returning has state!
    This state we also know to not natively support locking (similar to TPM
    resource manager, which locks and virtualises underlying TPM).
    """


class SystemContextOpConfig:
    system_context: SystemContext



@op(
    system_context=DataFlow(

    ),
)

@opsc(
    # Main package overlay will grab any DataFlow objects produced by other
    # installed overlays which consume the DataFlowToApplyAsOverlay Input.
    # It will output a results object with the "overlayed" key set to all of the
    # dataflows generated via other overlays, which consumed the
    # DataFlowToApplyAsOverlay.
    operations={
        "dataflow_todict": op(
            name="dataflow_todict",
            inputs={"dataflow": DataFlowBeingOverlayed},
            outputs={"dataflow_as_dict": DataFlowBeingOverlayedAsDict},
            multi_output=False,
        )(lambda dataflow: dataflow.export()),
        "merge": op(
            name="dataflow_merge",
            stage=Stage.OUTPUT,
            inputs={
                "dst": DataFlowBeingOverlayedAsDict,
                "src": DataFlowToApplyAsOverlay,
            },
            outputs={
                # TODO Full autogenerated definition name should reflect linage
                # of definition. Aka, this thing is a dict
                "merged_dataflow": UnusedDataFlowTypeAsDict,
            },
            multi_output=False,
        )(lambda dst, src: _merge(dst, src.export())),
        "dataflow_fromdict": op(
            name="dataflow_fromdict",
            stage=Stage.OUTPUT,
            inputs={
                "merged": DataFlowBeingOverlayedAsDict,
            },
            outputs={
                "overlays_merged": DataFlowAfterOverlaysMerged,
            },
            multi_output=False,
        )(lambda merged: DataFlow._fromdict(**merged)),
        "apply_overlay_to_dataflow_to_be_executed": op(
            name="dataflow_fromdict",
            stage=Stage.OUTPUT,
            inputs={
                "merged": DataFlowAfterOverlaysMerged,
                "dataflow_we_are_applying_overlays_to_by_running_overlay_dataflow_and_passing_as_an_input": DataFlowWeAreApplyingOverlaysToByRunningOverlayDataflowAndPassingAsAnInput,
            },
            outputs={
                "overlayed": DataFlowAfterOverlaysApplied,
            },
            multi_output=False,
        )(lambda merged: DataFlow._fromdict(**merged).update(auto_flow=True)),
    },
    seed=[
        Input(
            # Adding a blank flow ensures if there are no other
            # overlays, we just end up merging the input dataflow
            # with a blank overlay. Resulting in the return of the
            # original dataflow.
            value=DataFlow(),
            definition=DataFlowToApplyAsOverlay,
        ),
    ],
)
def git_set_file_contents_at_date(
    # When we serialize to/from web3 we'd see the repo object and the output of
    # this function be treated as NFTs, because we leverage NFTs for distriuted
    # locking. Can even get distributed semaphore functionality by leveraging
    # NFTs if you have a finite non 0/1 number of them
    repo: ReadWriteLock[GitRepository],
    date: DateToCommitGitRepoFileAt,
    filepath: FilePath,
) -> ReadWriteLock[GitRepositoryCheckedOut]:
    """
    Given a Git repository, set the contents of the given filepath to be the
    given contents within a commit with the date field matching the given date.

    We take the read write lock on the git repo when it comes in. Aka the caller
    should lock that object before calling this function! We also signal to the
    caller that if they use the returned object it we recommend that they lock
    it! If don't want to, that's up to them, but we recommend you lock it. As
    the producing operation, we understand that what we are returning has state!
    This state we also know to not natively support locking (similar to TPM
    resource manager, which locks and virtualises underlying TPM).
    """


Input(value=, definition=get_argument_datatype(git_set_file_contents_at_date, "date"))


INPUT = json.loads(pathlib.Path("output.json.formated.json").read_text())


def title_to_filename(title_link_line: str):
    title = title_link_line[2:]
    if "[" in title_link_line:
        title = title_link_line[3:]
        title = title[: title.index("]")]
    return title.upper().replace(":", "").replace(" ", "_").replace("-", "_")


def write_file():
        output_directory.joinpath(
            "_".join(["ROLLING", "ALICE", f"{0:04}"]) + ".md"
        ).write_text(discussion_node["discussion"]["body"],)


def output_markdown(
    graphql_query_output: dict, output_directory: pathlib.Path
):
    # Loop through all the pinned discussions
    for discussion_node in graphql_query_output["data"]["repository"][
        "pinnedDiscussions"
    ]["nodes"]:
        # Create the filename for the top level file
        filename = title_to_filename(
            discussion_node["discussion"]["body"].split("\n")[0]
        )
        output_directory.joinpath(
            "_".join(["ROLLING", "ALICE", f"{0:04}"]) + ".md"
        ).write_text(discussion_node["discussion"]["body"],)
        for i, comment_node in enumerate(
            discussion_node["discussion"]["comments"]["nodes"], start=1
        ):
            # Create the filename which will be joined by underscores
            filename_parts = ["ROLLING", "ALICE", f"{i:04}"]
            if comment_node["body"].split()[:1] == ["#"]:
                # If we are in a chapter. Create a directory
                filename_parts += [
                    title_to_filename(comment_node["body"].split("\n")[0])
                ]
            # Output a file for the comment
            output_directory.joinpath(
                "_".join(filename_parts) + ".md"
            ).write_text(comment_node["body"],)
            # Output a file for the reply
            for j, reply_node in enumerate(comment_node["replies"]["nodes"]):
                output_directory.joinpath(
                    "_".join(filename_parts + ["REPLY", f"{j:04}"]) + ".md"
                ).write_text(reply_node["body"],)


from typing import Any, Dict, NewType, Type, List

from ..base import replace_config
from ..df.types import Stage, DataFlow, Input, Definition
from ..operation.output import remap
from ..df.memory import MemoryOrchestrator
from ..df.base import op
from ..util.data import merge as _merge
from ..util.entrypoint import base_entry_point, Entrypoint


# TODO Unify this DataFlowType. Used as an example to show auto typing.NewType
# conversion to Definition (Definition is our pre-input linage based mechanism
# for identification of data type).
DataFlowType = NewType("dataflow", object)
# DataFlowTypeAsDict = cast(dict, DataFlowType)
# unittest.mock.patch have cast set val.typ = typ. Parse python source retrieved
# via inspect (stack frame code?) typecheck in the event mock.patch addition of typ not available at runtime.
DataFlowTypeAsDict = NewType("dict.dataflow", object)
UnusedDataFlowTypeAsDict = NewType("unused.dict.dataflow", dict)
DataFlowToApplyAsOverlay = NewType("DataFlowToApplyAsOverlay", DataFlow)
DataFlowWeAreApplyingOverlaysToByRunningOverlayDataflowAndPassingAsAnInput = NewType("DataFlowWeAreApplyingOverlaysToByRunningOverlayDataflowAndPassingAsAnInput", DataFlow)
DataFlowAfterOverlaysApplied = NewType("DataFlowAfterOverlaysApplied", DataFlow)

DataFlowBeingOverlayed = NewType("DataFlowBeingOverlayed", DataFlow)
DataFlowBeingOverlayedAsDict = NewType("DataFlowBeingOverlayedAsDict", DataFlow)
DataFlowAfterOverlaysMerged = NewType("DataFlowAfterOverlaysMerged", DataFlow)


# TODO Example of configurable return type for instance usage within DataFlow
@op
def overlays_installed(plugin_base: Entrypoint) -> List[DataFlowToApplyAsOverlay]:
    """
    Return a batch of overlays to be applied. The batch is given by searching
    the dffml.overlay entrypiont for installed registered overlays.
    """
    # TODO Have a plugin which itself is used to discover plugin types. We can
    # then reference by string and load the base class for that plugin type.
    # This is really just a stub for that more advanced abitrary version.
    # >>> Plugin.load("dffml.model")
    # Model
    # Iterate over all the installed overlays
    return cls.load()


# For inital overlay load of top level system context, we call
# overlays_installed to get all the dataflows which need to be merged. We then
# execute the merged installed overlays if LOAD_DEFAULT is given for
# ``overlay`` on ``run()``. Then we we run, the only default overlay added from
# the main package on install is one which defines an output operation which
# grabs all the dataflows within the input network of the running context for
# the overlay, merges them togther, and returns the to be run dataflow.
DFFML_MAIN_PACKAGE_OVERLAY = DataFlow(
    # Main package overlay will grab any DataFlow objects produced by other
    # installed overlays which consume the DataFlowToApplyAsOverlay Input.
    # It will output a results object with the "overlayed" key set to all of the
    # dataflows generated via other overlays, which consumed the
    # DataFlowToApplyAsOverlay.
    operations={
        "dataflow_todict": op(
            name="dataflow_todict",
            inputs={"dataflow": DataFlowBeingOverlayed},
            outputs={"dataflow_as_dict": DataFlowBeingOverlayedAsDict},
            multi_output=False,
        )(lambda dataflow: dataflow.export()),
        "merge": op(
            name="dataflow_merge",
            stage=Stage.OUTPUT,
            inputs={
                "dst": DataFlowBeingOverlayedAsDict,
                "src": DataFlowToApplyAsOverlay,
            },
            outputs={
                # TODO Full autogenerated definition name should reflect linage
                # of definition. Aka, this thing is a dict
                "merged_dataflow": UnusedDataFlowTypeAsDict,
            },
            multi_output=False,
        )(lambda dst, src: _merge(dst, src.export())),
        "dataflow_fromdict": op(
            name="dataflow_fromdict",
            stage=Stage.OUTPUT,
            inputs={
                "merged": DataFlowBeingOverlayedAsDict,
            },
            outputs={
                "overlays_merged": DataFlowAfterOverlaysMerged,
            },
            multi_output=False,
        )(lambda merged: DataFlow._fromdict(**merged)),
        "apply_overlay_to_dataflow_to_be_executed": op(
            name="dataflow_fromdict",
            stage=Stage.OUTPUT,
            inputs={
                "merged": DataFlowAfterOverlaysMerged,
                "dataflow_we_are_applying_overlays_to_by_running_overlay_dataflow_and_passing_as_an_input": DataFlowWeAreApplyingOverlaysToByRunningOverlayDataflowAndPassingAsAnInput,
            },
            outputs={
                "overlayed": DataFlowAfterOverlaysApplied,
            },
            multi_output=False,
        )(lambda merged: DataFlow._fromdict(**merged).update(auto_flow=True)),
    },
    seed=[
        Input(
            # Adding a blank flow ensures if there are no other
            # overlays, we just end up merging the input dataflow
            # with a blank overlay. Resulting in the return of the
            # original dataflow.
            value=DataFlow(),
            definition=DataFlowToApplyAsOverlay,
        ),
    ],
)


async def main():
    with tempfile.TemporaryDirectory() as tempdir:
        output_markdown(INPUT, pathlib.Path(tempdir))
        os.system(f"rm -rf 'docs/arch/alice/'")
        os.system(f"cp -r {tempdir} {pathlib.Path(os.getcwd(), 'docs/arch/alice/')}")
        async for ctx, results in dffml.run(
            dffml.DataFlow(),
            [
                Input(value=DataFlow(), definition=DataFlowBeingOverlayed)
            ],
        ):
            return results["overlayed"]



if __name__ == "__main__":
    asyncio.run(main())
