on:
  workflow_run:
    workflows:
      - "Test Workflow"
    types:
      - completed

# workflow-re-runs branch is used for tracking retry counts so we don't infinite
# retry
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  RETRY_COUNT_BRANCH: workflow-re-runs
  RUN_URL: ${{ github.event.workflow_run.url }}
  RUN_ID_TEST: ${{ github.event.workflow_run.id }}
  MAX_RETRIES: 5

jobs:
  re_run:
    name: Re-run job if needed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: workflow-re-runs
      - name: Get retrys
        run: |
          set -xe
          echo "RUN_ID_TEST=${RUN_ID_TEST}"
          RUN_ID=$(echo "${RUN_URL}" | sed -e 's/.*\///g')
          echo count=$(cat "${RUN_ID}" || echo 0) > "${GITHUB_OUTPUT}"
      - name: Increase re-run count
        run: |
          set -xe
          RUN_ID=$(echo "${RUN_URL}" | sed -e 's/.*\///g')
          count=$(($(cat "${RUN_ID}" || echo 0) + 1)) > "${RUN_ID}"
      - name: Push branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -xe
          gh auth setup-git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --amend --no-edit
          git push -uf origin "HEAD:${RETRY_COUNT_BRANCH}"
      - name: Trigger re-run
        if: ${{ fromJSON(steps.get-retries.outputs.count) < fromJSON(env.MAX_RETRIES) }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -xe
          RUN_ID=$(echo "${RUN_URL}" | sed -e 's/.*\///g')
          gh run rerun "${RUN_ID}"

  cleanup_re_run_tracking:
    name: Cleanup workflow-re-runs branch used for tracking retry counts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: workflow-re-runs
      - name: Remove re-run count
        run: |
          set -xe
          RUN_ID=$(echo "${RUN_URL}" | sed -e 's/.*\///g')
          rm -vf "${RUN_ID}"
      - name: Push branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -xe
          gh auth setup-git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --amend --no-edit
          git push -uf origin "HEAD:${RETRY_COUNT_BRANCH}"
