name: "Test Workflow"

on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello World
          exit 1
