name: Tests

on:
  push:
    paths-ignore:
    - 'docs/arch/**'
  pull_request:
    paths-ignore:
    - 'docs/arch/**'
  schedule:
  - cron:  '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        python-version:
        - 3.7

    steps:
    - uses: actions/checkout@v2
    - name: Checkout full upstream repo
      run: |
        git remote set-url origin https://github.com/intel/dffml
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git config --global user.email "dffml@intel.com"
        git config --global user.name "DFFML CI/CD"
        git checkout 5635dc8badc5efd914576ec047ba906777dc94df
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        set -x
        python -m pip install -U pip setuptools wheel
        python -m pip install . model/scikit
    - name: Predict
      shell: python -u {0}
      run: |
        # Example showing how to predict migration headcount and time required (max
        # taken from sample and sum taken for headcount) for an organization.
        import asyncio

        import dffml

        ScikitRidgeModel = dffml.Model.load("scikitridge")

        features = dffml.Features(
            dffml.Feature("org_headcount", int, 1),
        )
        predict_features = dffml.Features(
            dffml.Feature("weeks", int, 1), dffml.Feature("headcount", int, 1),
        )

        multi_reg_model = ScikitRidgeModel(
            features=features, predict=predict_features, location="scikitridgemulti",
        )


        async def main():
            await dffml.train(
                multi_reg_model,
                {"weeks": 8, "headcount": 7, "org_headcount": 524},
                {"weeks": 12, "headcount": 17, "org_headcount": 1122},
            )

            async for i, features, prediction in dffml.predict(
                multi_reg_model,
                {"org_headcount": 17368},
            ):
                print(prediction)


        if __name__ == "__main__":
            asyncio.run(main())
